---
singletons:
- javax.sql.DataSource:
  - com.zaxxer.hikari.HikariDataSource:
      DriverClassName: org.h2.jdbcx.JdbcDataSource
      jdbcUrl: jdbc:h2:~/test
      username: sa
      password: sa
- com.networknt.saga.core.message.producer.MessageProducer:
  - com.networknt.saga.repository.MessageProducerJdbcImpl
- com.networknt.saga.repository.SagaInstanceRepository:
  - com.networknt.saga.repository.SagaInstanceRepositoryJdbc
- com.networknt.saga.participant.SagaLockManager:
  - com.networknt.saga.repository.SagaLockManagerImpl
- com.networknt.saga.repository.EnlistedAggregatesDao:
  - com.networknt.saga.repository.EnlistedAggregatesDaoImpl
- com.networknt.saga.repository.AggregateInstanceSubscriptionsDAO:
  - com.networknt.saga.repository.AggregateInstanceSubscriptionsDAOImpl
- com.networknt.saga.core.events.publisher.DomainEventPublisher:
  - com.networknt.saga.core.events.publisher.DomainEventPublisherImpl