---
singletons:
- javax.sql.DataSource:
  - com.zaxxer.hikari.HikariDataSource:
      DriverClassName: org.h2.jdbcx.JdbcDataSource
      jdbcUrl: jdbc:h2:~/test
      username: sa
      password: sa
- com.networknt.saga.core.message.producer.MessageProducer:
  - com.networknt.saga.repository.MessageProducerJdbcImpl
- com.networknt.saga.orchestration.SagaInstanceRepository:
  - com.networknt.saga.orchestration.SagaInstanceRepositoryJdbc
- com.networknt.saga.participant.SagaLockManager:
  - com.networknt.saga.participant.SagaLockManagerImpl
- com.networknt.saga.orchestration.EnlistedAggregatesDao:
  - com.networknt.saga.orchestration.EnlistedAggregatesDaoImpl
- com.networknt.saga.orchestration.AggregateInstanceSubscriptionsDAO:
  - com.networknt.saga.orchestration.AggregateInstanceSubscriptionsDAOImpl
- com.networknt.saga.consumer.DuplicateMessageDetector:
  - com.networknt.saga.repository.SqlTableBasedDuplicateMessageDetector
- com.networknt.saga.core.events.publisher.DomainEventPublisher:
  - com.networknt.saga.core.events.publisher.DomainEventPublisherImpl